#!/usr/bin/env bash
# This script configures nginx to listen on port 8080 of active IP(s)
#+ It runs nginx as nginx instead of the root user.

sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/\[::\]:80/\[::\]:8080/g' /etc/nginx/sites-available/default
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
